# Generated by Django 2.2.20 on 2021-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BooleanField(verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, verbose_name='Цена по скидке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_disc',
            field=models.CharField(max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
