# Generated by Django 2.2.20 on 2021-05-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210524_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='static/img/', verbose_name='Фото'),
        ),
    ]
