# Generated by Django 2.2.20 on 2021-05-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210524_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
